### ISSUE TITLE
Create a 1.6 release

### ISSUE THREAD

**Issue by dmlloyd** [kohsuke/metainf-services#5]
I know only the one warning was really fixed since 1.5, but that one warning is kind of annoying. :)

Any chance for a 1.6 release/deploy to maven?

**Comment by HNygard** [comment]
+1

Can the fixed warnings be release? @kohsuke @jglick

**Comment by HNygard** [comment]
Regarding issue #3, pull request #4 and commit be84ce99e8f0c5da6034788d77dc818aa0e1e06a

**Comment by jglick** [comment]
I think up to @kohsuke to cut releases.

**Comment by kohsuke** [comment]
Done after a long delay.
